---
- hosts: localhost
  connection: local
  become: true

  vars: 
    homeDir: "{{ lookup('env', 'HOME') }}"
    nvimConfigSrc: "{{ lookup('env', 'PWD' }}/files/nvim"
    nvimConfigDest: "{{ homeDir }}/.config/nvim"

  tasks:

    - name: Print present working directory
      debug:

    - name: apt update
      apt:
        update_cache: yes

    - name: install packages
      package:
          name:
            - zsh
            - tmux
            - g++

    - name: snap install nvim --classic
      community.general.snap:
        name: 'nvim'
        classic: yes

    - name: symlink configs
      file:
         src: "{{ nvimConfigSrc }}"
         dest: "{{ nvimConfigDest }}"
         state: link
         force: yes
         owner: root

