---
- hosts: localhost
  connection: local
  become: true
  vars: 
    homeDir: "/home/zyr"
    testDir: "{{ homeDir }}/.config/nvim"
    nvimConfigSrc: "/home/zyr/personal/ansible/files/nvim"
    nvimConfigDest: "/home/zyr/.config/nvim"

  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: install packages
      package:
          name:
            - zsh
            - tmux
            - g++

    - name: snap install nvim --classic
      community.general.snap:
        name: 'nvim'
        classic: yes

    - name: symlink configs
      ansible.builtin.file:
         src: "{{ nvimConfigSrc }}"
         dest: "{{ testDir }}"
         state: link
         force: yes
         owner: zyr
