---
- hosts: localhost
  connection: local
  become: true

  vars: 
    homeDir: "{{ lookup('env', 'HOME') }}"
    localPWD: "{{ lookup('env', 'PWD') }}"
    nvimConfigSrc: "{{ localPWD }}/files/nvim"
    nvimConfigDest: "{{ homeDir }}/.config/nvim"

  tasks:

    - name: Print present working directory
      debug:
        var: localPWD

    - name: apt update
      apt:
        update_cache: yes

    - name: install packages
      package:
          name:
            - zsh
            - tmux
            - g++

    - name: snap install nvim --classic
      community.general.snap:
        name: 'nvim'
        classic: yes

    - name: symlink configs
      file:
        src: files/nvim
        dest: "{{ nvimConfigDest }}"

