---
- hosts: localhost
  connection: local
  become: true

  vars: 
    homeDir: "{{ lookup('env', 'HOME') }}"
    nvimConfigDest: "{{ homeDir }}/.config/nvim"
    localPWD: "{{ lookup('env', 'PWD') }}"
    nvimConfigSrc: "{{ homeDir }}/.ansible/pull/{{ ansible_hostname }}./files/nvim"

  tasks:

    - name: Print present working directory
      debug:
        var: nvimConfigSrc

    - name: apt update
      apt:
        update_cache: yes

    - name: install packages
      package:
          name:
            - zsh
            - tmux
            - g++

    - name: snap install nvim --classic
      snap:
        name: 'nvim'
        classic: yes

    - name: symlink configs
      file:
        src: "{{ nvimConfigSrc }}"
        dest: "{{ nvimConfigDest }}"
        force: true

