---
- hosts: localhost
  connection: local
  become: true
  vars: 
    nvimConfigSrc: "/files/nvim"
    nvimConfigDest: "~/.config/nvim"

  tasks:
    - name: debug
      debug: var={{ $HOME }}
    
    - name: apt update
      apt:
        update_cache: yes

    - name: install packages
      package:
          name:
            - zsh
            - tmux

    - name: snap install nvim --classic
      community.general.snap:
        name: 'nvim'
        classic: yes

    - name: symlink configs
      ansible.builtin.file:
         src: "{{ nvimConfigSrc }}"
         dest: "{{ nvimConfigDest }}"
         state: link
         owner: root
         group: root
         force: yes
